# CypressによるE2Eテスト
on: pull_request

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest commit
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
